Create a pandas DataFrame containing the provided student dataset.

In [1]:
import pandas as pd

data = {
    "StudentID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Alice","Bob","Charles","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age": [20,21,19,22,20,21,23,19,22,20],
    "Marks": [88,75,92,65,78,85,70,95,60,80],
    "Grade": ["A","B","A","C","B","A","B","A","C","B"]
}

df = pd.DataFrame(data)

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charles   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

Save the DataFrame to a CSV file named students.csv.

In [2]:

df.to_csv("students.csv", index=False)

print("File saved successfully.")

File saved successfully.

Reload the dataset from the saved CSV file into a new DataFrame.

In [3]:

df = pd.read_csv("students.csv")

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charles   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

Display the first three rows of the dataset using df.head().

In [4]:
df.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charles   19     92     A


Generate descriptive statistics for numeric columns using df.describe().

In [5]:
df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

Display the number of rows and columns in the dataset using df.shape.

In [6]:
df.shape

(10, 5)

Display the data type of each column in the DataFrame.

In [8]:
df.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

Show detailed information about the DataFrame including column types and non-null counts.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes