Task 1 - Create the Pandas DataFrame

In [1]:
import pandas as pd

# Data for students
data = {
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah', 'Ivan', 'Julia'],
    'Age': [20, 21, 19, 22, 20, 21, 23, 19, 22, 20],
    'Marks': [88, 75, 92, 65, 78, 85, 70, 95, 60, 80],
    'Grade': ['A', 'B', 'A', 'C', 'B', 'A', 'B', 'A', 'C', 'B']
}

# Create DataFrame
students_df = pd.DataFrame(data)

# Display the DataFrame
students_df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

Task 2 - Save the DataFrame as a CSV file

In [2]:
# Save DataFrame as CSV file
students_df.to_csv('students.csv', index=False)

Above code saves the DataFrame students_df to a CSV file(students.csv), index = false used for exclude the index column.

Task 3 - Reload the CSV file into a new DataFrame

In [3]:
# Reload the CSV file into a new DataFrame
df_reload = pd.read_csv('students.csv')

# Display the DataFrame to verify
df_reload

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

ABove code reload the csv data into new dataframe

Task 4 - Display the first 3 rows

In [4]:
# Display the first 3 rows
df_reload.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

Task 5 - Display the statistical summary

In [5]:
# Display the statistical summary
df_reload.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

describe() displays the statistical summary (e.g. mean,standard deviation,min,max)

Task 6 - Explore the DataFrame using .shape, .dtypes, and .info()

In [6]:
# Display the shape of the DataFrame
df_reload.shape

# Display the data types of each column
df_reload.dtypes

# Display detailed information about the DataFrame
df_reload.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     str
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     str
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

1) shape returns the number of rows and columns.

2) dtypes shows the data types of each column.

3) info() provides more detailed information, such as the number of non-null entries in each column.